function schema(example: Record<string, unknown>, properties: Record<string, unknown>, required?: string[]) {
  return {
    "1": {
      type: "object",
      properties: {
        eventType: { type: "string" },
        workspaceId: { type: "string", format: "uuid" },
        data: {
          type: "object",
          properties,
          required: required ?? Object.keys(properties),
        },
        timestamp: { type: "string", format: "date-time" },
        actorId: { type: "string" },
      },
      examples: [example],
    },
  };
}

export const EVENT_TYPES = [
  {
    name: "link.created",
    description: "A new short link was created in a workspace",
    schemas: schema(
      {
        linkId: "3f4a1b2c-1234-5678-abcd-ef0123456789",
        slug: "summer-sale",
        destination: "https://acmecorp.com/sale",
        domain: "go.acmecorp.com",
        title: "Summer Sale 2026",
        tags: ["campaign:summer", "team:marketing"],
        utmSource: "email",
        utmMedium: "newsletter",
        utmCampaign: "summer-sale-2026",
        hasExpiry: true,
        hasPassword: false,
        hasClickLimit: false,
        abTestEnabled: false,
        hasSmartRouting: false,
      },
      {
        linkId: { type: "string", description: "UUID of the created link" },
        slug: { type: "string", description: "The short link slug" },
        destination: { type: "string", format: "uri", description: "The destination URL" },
        domain: { type: "string", description: "The domain used for the short link" },
        title: { type: "string", description: "Optional display name for the link" },
        tags: { type: "array", items: { type: "string" }, description: "Tags attached to the link" },
        utmSource: { type: "string", description: "UTM source parameter" },
        utmMedium: { type: "string", description: "UTM medium parameter" },
        utmCampaign: { type: "string", description: "UTM campaign parameter" },
        utmTerm: { type: "string", description: "UTM term parameter" },
        utmContent: { type: "string", description: "UTM content parameter" },
        abTestEnabled: { type: "boolean", description: "Whether A/B testing is active" },
        hasExpiry: { type: "boolean", description: "Whether the link has an expiry set" },
        hasClickLimit: { type: "boolean", description: "Whether the link has a click limit" },
        hasPassword: { type: "boolean", description: "Whether the link is password-protected" },
        hasSmartRouting: { type: "boolean", description: "Whether geo/device/language routing is configured" },
      },
    ),
    archived: false,
  },
  {
    name: "link.updated",
    description: "A short link was updated — only changed fields are included in changes",
    schemas: schema(
      {
        linkId: "3f4a1b2c-1234-5678-abcd-ef0123456789",
        slug: "summer-sale",
        destination: "https://acmecorp.com/sale",
        domain: "go.acmecorp.com",
        updatedBy: "user_abc123",
        changes: {
          destination: { from: "https://acmecorp.com/sale", to: "https://acmecorp.com/sale-extended" },
          isActive: { from: true, to: true },
        },
      },
      {
        linkId: { type: "string", description: "UUID of the updated link" },
        slug: { type: "string", description: "The short link slug" },
        destination: { type: "string", format: "uri", description: "Current destination URL" },
        domain: { type: "string", description: "The domain used for the short link" },
        updatedBy: { type: "string", description: "User ID who made the change" },
        changes: {
          type: "object",
          description: "Map of changed fields with { from, to } values",
          properties: {
            destination: { type: "object", properties: { from: { type: "string" }, to: { type: "string" } } },
            title: { type: "object", properties: { from: { type: "string" }, to: { type: "string" } } },
            isActive: { type: "object", properties: { from: { type: "boolean" }, to: { type: "boolean" } } },
            tags: { type: "object", properties: { from: { type: "array", items: { type: "string" } }, to: { type: "array", items: { type: "string" } } } },
            expiresAt: { type: "object", properties: { from: { type: "string" }, to: { type: "string" } } },
            clickLimit: { type: "object", properties: { from: { type: "integer" }, to: { type: "integer" } } },
            utmSource: { type: "object", properties: { from: { type: "string" }, to: { type: "string" } } },
            utmMedium: { type: "object", properties: { from: { type: "string" }, to: { type: "string" } } },
            utmCampaign: { type: "object", properties: { from: { type: "string" }, to: { type: "string" } } },
          },
        },
      },
      ["linkId", "slug", "changes"],
    ),
    archived: false,
  },
  {
    name: "link.deleted",
    description: "A short link was permanently deleted from a workspace",
    schemas: schema(
      {
        linkId: "3f4a1b2c-1234-5678-abcd-ef0123456789",
        slug: "old-campaign",
        destination: "https://acmecorp.com/old",
        domain: "go.acmecorp.com",
        title: "Old Campaign Link",
        totalClicks: 4823,
        deletedBy: "user_abc123",
      },
      {
        linkId: { type: "string" },
        slug: { type: "string" },
        destination: { type: "string", format: "uri" },
        domain: { type: "string" },
        title: { type: "string", description: "Display name of the deleted link" },
        totalClicks: { type: "integer", description: "Total clicks the link had before deletion" },
        deletedBy: { type: "string", description: "User ID who deleted the link" },
      },
      ["linkId", "slug", "domain"],
    ),
    archived: false,
  },
  {
    name: "link.clicked",
    description: "A short link received a click — high-frequency event with full geo, device, and referrer context",
    schemas: schema(
      {
        linkId: "3f4a1b2c-1234-5678-abcd-ef0123456789",
        slug: "summer-sale",
        domain: "go.acmecorp.com",
        country: "IN",
        city: "Mumbai",
        region: "Maharashtra",
        device: "iPhone",
        deviceType: "ios",
        browser: "Safari",
        browserVersion: "17.4.1",
        os: "iOS",
        osVersion: "17.4.1",
        referrer: "https://twitter.com/",
        referrerDomain: "twitter.com",
        referrerType: "social",
        utmSource: "twitter",
        utmMedium: "social",
        utmCampaign: "summer-sale-2026",
        isBot: false,
        isQrScan: false,
        ipHash: "a3f8b2c1d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a",
      },
      {
        linkId: { type: "string", description: "UUID of the clicked link" },
        slug: { type: "string" },
        domain: { type: "string" },
        country: { type: "string", description: "ISO 3166-1 alpha-2 country code" },
        city: { type: "string", description: "City name of the visitor" },
        region: { type: "string", description: "Region/state of the visitor" },
        device: { type: "string", description: "Device name e.g. iPhone, Desktop" },
        deviceType: { type: "string", enum: ["ios", "android", "desktop", "tablet", "mobile", "bot"], description: "Device category" },
        browser: { type: "string", description: "Browser name e.g. Chrome, Safari" },
        browserVersion: { type: "string", description: "Browser version" },
        os: { type: "string", description: "Operating system name" },
        osVersion: { type: "string", description: "Operating system version" },
        referrer: { type: "string", description: "Full referrer URL" },
        referrerDomain: { type: "string", description: "Referrer domain e.g. twitter.com" },
        referrerType: { type: "string", enum: ["direct", "search", "social", "email", "referral"], description: "Traffic source type" },
        utmSource: { type: "string", description: "UTM source from query string" },
        utmMedium: { type: "string", description: "UTM medium from query string" },
        utmCampaign: { type: "string", description: "UTM campaign from query string" },
        utmTerm: { type: "string" },
        utmContent: { type: "string" },
        abVariant: { type: "string", description: "Destination URL of the A/B variant served" },
        isBot: { type: "boolean", description: "True if User-Agent matches a known bot pattern" },
        isQrScan: { type: "boolean", description: "True if the click came from a QR code scan" },
        ipHash: { type: "string", description: "SHA-256 hash of the visitor IP for unique counting" },
        timestamp: { type: "integer", description: "Click time in Unix milliseconds" },
      },
      ["linkId", "slug", "domain", "country", "device", "referrerType"],
    ),
    archived: false,
  },
  {
    name: "conversion.tracked",
    description: "A tracked conversion was attributed to a link click — connects clicks to revenue",
    schemas: schema(
      {
        linkId: "3f4a1b2c-1234-5678-abcd-ef0123456789",
        slug: "summer-sale",
        conversionId: "conv_7b8c9d0e-1234-5678-abcd-ef0123456789",
        event: "purchase",
        value: 149.99,
        currency: "USD",
        attributionModel: "last_touch",
        creditPercentage: 100,
        creditValue: 149.99,
        customerEmail: "buyer@example.com",
      },
      {
        linkId: { type: "string" },
        slug: { type: "string" },
        conversionId: { type: "string", description: "Unique conversion identifier" },
        event: { type: "string", description: "Conversion event name e.g. purchase, signup, trial_start" },
        value: { type: "number", description: "Monetary value of the conversion" },
        currency: { type: "string", description: "ISO 4217 currency code" },
        attributionModel: { type: "string", enum: ["first_touch", "last_touch", "linear", "time_decay"], description: "Attribution model used" },
        creditPercentage: { type: "integer", description: "Percentage of conversion credited to this link (0-100)" },
        creditValue: { type: "number", description: "Computed credit value = value * (creditPercentage / 100)" },
        customerId: { type: "string", description: "Your own customer identifier" },
        customerEmail: { type: "string", format: "email", description: "Customer email" },
        touchpointPosition: { type: "integer", description: "Position of this link in the customer journey" },
        totalTouchpoints: { type: "integer", description: "Total touchpoints in the conversion journey" },
        metadata: { type: "object", description: "Optional custom conversion metadata" },
      },
      ["linkId", "slug", "conversionId", "event", "attributionModel"],
    ),
    archived: false,
  },
  {
    name: "workspace.member_added",
    description: "A new member was added to a workspace",
    schemas: schema(
      { memberId: "user_...", memberEmail: "collaborator@example.com", role: "member", addedBy: "admin_..." },
      {
        memberId: { type: "string", description: "The user ID of the new member" },
        memberEmail: { type: "string", format: "email" },
        role: { type: "string", enum: ["admin", "member", "viewer"] },
        addedBy: { type: "string", description: "The user ID who added the member" },
      },
      ["memberId", "role"],
    ),
    archived: false,
  },
  {
    name: "workspace.member_removed",
    description: "A member was removed from a workspace",
    schemas: schema(
      { memberId: "user_...", memberEmail: "collaborator@example.com", role: "member", removedBy: "admin_..." },
      {
        memberId: { type: "string" },
        memberEmail: { type: "string", format: "email" },
        role: { type: "string", enum: ["admin", "member", "viewer"] },
        removedBy: { type: "string", description: "The user ID who removed the member" },
      },
      ["memberId"],
    ),
    archived: false,
  },
  {
    name: "workspace.plan_changed",
    description: "The workspace plan was upgraded or downgraded",
    schemas: schema(
      { fromPlan: "free", toPlan: "pro", eventType: "payment.succeeded" },
      {
        fromPlan: { type: "string", description: "Previous plan name" },
        toPlan: { type: "string", description: "New plan name" },
        eventType: { type: "string", description: "The billing event that triggered the change" },
      },
      ["fromPlan", "toPlan"],
    ),
    archived: false,
    featureFlags: ["admin"],
  },
  {
    name: "domain.verified",
    description: "A custom domain passed DNS verification and became active",
    schemas: schema(
      {
        domainId: "dom_2c3d4e5f-6789-01ab-cdef-012345678901",
        domain: "go.acmecorp.com",
        cnameTarget: "proxy.linkfor.ge",
        sslStatus: "active",
        isDefault: true,
        workspacePlan: "growth",
      },
      {
        domainId: { type: "string" },
        domain: { type: "string", format: "hostname" },
        cnameTarget: { type: "string", description: "The CNAME target the domain points to" },
        sslStatus: { type: "string", enum: ["active", "pending", "failed"], description: "SSL certificate status" },
        isDefault: { type: "boolean", description: "Whether this is the workspace default domain" },
        workspacePlan: { type: "string", description: "The workspace plan at time of verification" },
      },
      ["domainId", "domain", "sslStatus"],
    ),
    archived: false,
  },
  {
    name: "domain.deleted",
    description: "A custom domain was deleted from a workspace",
    schemas: schema(
      { domainId: "dom_...", domain: "links.example.com" },
      {
        domainId: { type: "string" },
        domain: { type: "string", format: "hostname" },
      },
    ),
    archived: false,
  },
  {
    name: "qr.created",
    description: "A QR code was created for a link",
    schemas: schema(
      { qrId: "qr_...", linkId: "clx...", slug: "my-slug", format: "png" },
      {
        qrId: { type: "string" },
        linkId: { type: "string" },
        slug: { type: "string" },
        format: { type: "string", enum: ["png", "svg", "jpeg"], description: "QR code image format" },
      },
    ),
    archived: false,
  },
  {
    name: "qr.updated",
    description: "A QR code configuration was updated",
    schemas: schema(
      { qrId: "qr_...", linkId: "clx...", slug: "my-slug", changes: ["format", "fgColor"] },
      {
        qrId: { type: "string" },
        linkId: { type: "string" },
        slug: { type: "string" },
        changes: { type: "array", items: { type: "string" } },
      },
    ),
    archived: false,
  },
  {
    name: "qr.deleted",
    description: "A QR code was deleted",
    schemas: schema(
      { qrId: "qr_...", linkId: "clx...", slug: "my-slug" },
      {
        qrId: { type: "string" },
        linkId: { type: "string" },
        slug: { type: "string" },
      },
    ),
    archived: false,
  },
  {
    name: "qr.scanned",
    description: "A QR code linked to a short link was scanned — fires alongside link.clicked",
    schemas: schema(
      {
        qrId: "qr_5e6f7a8b-9012-3456-cdef-012345678901",
        linkId: "3f4a1b2c-1234-5678-abcd-ef0123456789",
        slug: "menu",
        domain: "go.acmecorp.com",
        country: "US",
        city: "Chicago",
        region: "Illinois",
        device: "iPhone",
        deviceType: "ios",
        os: "iOS",
        osVersion: "17.3.1",
      },
      {
        qrId: { type: "string", description: "UUID of the QR code config used" },
        linkId: { type: "string" },
        slug: { type: "string" },
        domain: { type: "string" },
        country: { type: "string", description: "ISO 3166-1 alpha-2 country code" },
        city: { type: "string", description: "City of the scanner" },
        region: { type: "string", description: "Region/state of the scanner" },
        device: { type: "string", description: "Device name" },
        deviceType: { type: "string", enum: ["ios", "android", "tablet", "mobile"], description: "Device category" },
        os: { type: "string" },
        osVersion: { type: "string" },
        frameStyle: { type: "string", enum: ["none", "border", "scan-me"], description: "QR code frame style" },
      },
      ["qrId", "linkId", "slug", "domain", "country"],
    ),
    archived: false,
  },
  {
    name: "link_gallery.published",
    description: "A Link-in-Bio gallery page was published or made live",
    schemas: schema(
      { galleryId: "gal_...", slug: "my-bio", title: "My Links" },
      {
        galleryId: { type: "string" },
        slug: { type: "string" },
        title: { type: "string" },
      },
    ),
    archived: false,
  },
  {
    name: "link_gallery.updated",
    description: "A Link-in-Bio gallery page was updated",
    schemas: schema(
      { galleryId: "gal_...", slug: "my-bio", changes: ["title", "theme"] },
      {
        galleryId: { type: "string" },
        slug: { type: "string" },
        changes: { type: "array", items: { type: "string" } },
      },
    ),
    archived: false,
  },
  {
    name: "link_gallery.viewed",
    description: "A Link-in-Bio gallery page was viewed by a visitor — fires on each page load",
    schemas: schema(
      {
        galleryId: "gal_...",
        slug: "my-bio",
        username: "srikanth",
        country: "IN",
        city: "Bengaluru",
        region: "Karnataka",
        device: "Android Phone",
        deviceType: "android",
        browser: "Chrome",
        os: "Android",
        referrer: "https://www.instagram.com/",
        referrerType: "social",
        isUniqueView: true,
      },
      {
        galleryId: { type: "string", description: "UUID of the gallery page" },
        slug: { type: "string", description: "Public slug of the gallery" },
        username: { type: "string", description: "The public-facing username" },
        country: { type: "string", description: "ISO 3166-1 alpha-2 country code" },
        city: { type: "string" },
        region: { type: "string" },
        device: { type: "string" },
        deviceType: { type: "string", enum: ["ios", "android", "desktop", "tablet", "mobile"] },
        browser: { type: "string" },
        os: { type: "string" },
        referrer: { type: "string", description: "Referrer URL" },
        referrerType: { type: "string", enum: ["direct", "search", "social", "email", "referral"] },
        isUniqueView: { type: "boolean", description: "True if this visitor has not viewed this page before (30-day window)" },
      },
      ["galleryId", "slug", "country", "device", "referrerType"],
    ),
    archived: false,
  },
  {
    name: "link.flagged_malicious",
    description: "Cloudflare URL Scanner flagged a link's destination as malicious — fired on band transition into 'low'",
    schemas: schema(
      {
        linkId: "lk_...",
        scanId: "095be615-a8ad-4c33-8e9c-c7612fbf6c9f",
        trustScore: 12,
        trustBand: "low",
        malicious: true,
      },
      {
        linkId: { type: "string", description: "UUID of the link" },
        scanId: { type: "string", description: "Cloudflare URL Scanner scan UUID" },
        trustScore: { type: "integer", minimum: 0, maximum: 100 },
        trustBand: { type: "string", enum: ["unknown", "low", "medium", "high", "verified"] },
        malicious: { type: "boolean" },
      },
      ["linkId", "scanId", "trustScore", "trustBand"],
    ),
    archived: false,
  },
  {
    name: "link.flagged_safe",
    description: "A previously-flagged link's destination is no longer malicious — fired on band transition out of 'low'",
    schemas: schema(
      {
        linkId: "lk_...",
        scanId: "095be615-a8ad-4c33-8e9c-c7612fbf6c9f",
        trustScore: 78,
        trustBand: "high",
      },
      {
        linkId: { type: "string", description: "UUID of the link" },
        scanId: { type: "string", description: "Cloudflare URL Scanner scan UUID" },
        trustScore: { type: "integer", minimum: 0, maximum: 100 },
        trustBand: { type: "string", enum: ["unknown", "low", "medium", "high", "verified"] },
      },
      ["linkId", "scanId", "trustScore", "trustBand"],
    ),
    archived: false,
  },
] as const;

export type PivotUrlEventType = (typeof EVENT_TYPES)[number]["name"];
