import * as dotenv from 'dotenv';
import { neon } from '@neondatabase/serverless';

dotenv.config({ path: '.env.local' });

/**
 * Adds the `published_snapshot` and `published_at` columns to `link_gallery`.
 *
 * Idempotent — uses `IF NOT EXISTS` so re-running is a no-op. Decoupled from
 * drizzle-kit's autogenerated migrations because the snapshot diff is currently
 * out of sync with the live DB and would emit spurious CREATE TABLE statements.
 */
async function run() {
  const url = process.env.DATABASE_URL;
  if (!url) {
    console.error('DATABASE_URL not set');
    process.exit(1);
  }
  const sql = neon(url);

  console.log('[add-published-snapshot] Adding columns to link_gallery…');

  await sql`
    ALTER TABLE "link_gallery"
      ADD COLUMN IF NOT EXISTS "published_snapshot" jsonb DEFAULT NULL
  `;
  await sql`
    ALTER TABLE "link_gallery"
      ADD COLUMN IF NOT EXISTS "published_at" timestamp with time zone
  `;

  // Quick sanity check
  const cols = await sql`
    SELECT column_name, data_type
    FROM information_schema.columns
    WHERE table_name = 'link_gallery'
      AND column_name IN ('published_snapshot', 'published_at')
    ORDER BY column_name
  `;
  console.log('[add-published-snapshot] Columns now present:', cols);
  console.log('[add-published-snapshot] Done.');
}

run().catch((err) => {
  console.error('[add-published-snapshot] failed', err);
  process.exit(1);
});
